spring:
  application:
    name: spaceship-api

  datasource:
    url: jdbc:h2:mem:spaceship-db
    driver-class-name: org.h2.Driver
    username: sa
    password: sa

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false

  h2:
    console:
      enabled: true

  flyway:
    enabled: true
    locations: classpath:db/migrations
    user: sa
    password: sa

  kafka:
    bootstrap-servers: localhost:9092
    topic: spaceship-events

  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    org:
      flywaydb: DEBUG
