spring:
  application:
    name: spaceship-api

  datasource:
    url: jdbc:h2:mem:spaceship-db
    driver-class-name: org.h2.Driver
    username: sa
    password: sa

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true

