
spring:
  application:
    name: spaceship-api

  datasource:
    url: jdbc:h2:mem:spaceship-db
    driver-class-name: org.h2.Driver
    username: sa
    password: sa

  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true

  h2:
    console:
      enabled: true

  flyway:
    enabled: true
    locations: classpath:db/migrations
    user: sa
    password: sa

logging:
  level:
    org:
      flywaydb: DEBUG
